stages:
  prepare_error_data:
    cmd: python src/prepare/preprocessing_error.py
    deps:
    - data/raw/errors/S19errors.csv
    outs:
    - data/prepared/errors/error_MainTable.csv
    - data/prepared/errors/submission_error_list.csv
    - data/prepared/errors/submission_list.csv
  prepare_code_data:
    cmd:
    - python src/prepare/preprocessing.py
    - python src/prepare/path_extractor.py
    deps:
    - data/prepared/errors/error_MainTable.csv
    - data/raw/CodeStates
    outs:
    - data/prepared/DKTFeatures_439
  prepare_question_data:
    cmd: python src/prepare/preprocessing_question.py
    deps:
    - data/raw/MainTable.csv
    - data/raw/question/concepts.csv
    - data/raw/question/prompt_concept.csv
    outs:
    - data/prepared/question/id_pro_dict.txt
    - data/prepared/question/pro_feat.npz
    - data/prepared/question/pro_id_dict.txt
    - data/prepared/question/pro_pro_sparse.npz
    - data/prepared/question/pro_skill_sparse.npz
    - data/prepared/question/skill_id_dict.txt
    - data/prepared/question/skill_skill_sparse.npz
    - data/prepared/question/combined_concepts.csv
  train_bipartite_graph:
    cmd: python src/prepare/run_pebg.py
    deps:
    - data/prepared/question/id_pro_dict.txt
    - data/prepared/question/pro_feat.npz
    - data/prepared/question/pro_id_dict.txt
    - data/prepared/question/pro_pro_sparse.npz
    - data/prepared/question/pro_skill_sparse.npz
    - data/prepared/question/skill_id_dict.txt
    - data/prepared/question/skill_skill_sparse.npz
    outs:
    - data/prepared/question/embedding
    - data/prepared/question/pebg_model
